id: P5594D247
initial_creation_type: ocr
source_metadata:
  volumes:
    8ec7ba747df840ccbf12ed9f64cc0b0c:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: རིགས་པའི་ཐིགས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1198
      volume_number: 97
